//
//  Country.swift
//  CyberWiseMain
//
//  Created by GUILHERME JULIO on 19/01/2025.
//

import Foundation
import SwiftUI

struct Country: Identifiable {
    let id = UUID()
    let name: String        // e.g. "United States"
    let code: String        // e.g. "+1"
    let isoCode: String     // e.g. "US"
    let flag: String        // e.g. "🇺🇸"
}


let countries: [Country] = [
        Country(name: "Afghanistan", code: "+93", isoCode: "AF", flag: "🇫🇷"),
        Country(name: "Albania", code: "+355", isoCode: "AL", flag: "🇦🇱"),
        Country(name: "Algeria", code: "+213", isoCode: "DZ", flag: "🇩🇿"),
        Country(name: "Andorra", code: "+376", isoCode: "AD", flag: "🇦🇩"),
        Country(name: "Angola", code: "+244", isoCode: "AO", flag: "🇦🇴"),
        Country(name: "Antigua and Barbuda", code: "+1-268", isoCode: "AG", flag: "🇦🇬"),
        Country(name: "Argentina", code: "+54", isoCode: "AR", flag: "🇦🇷"),
        Country(name: "Armenia", code: "+374", isoCode: "AM", flag: "🇦🇲"),
        Country(name: "Australia", code: "+61", isoCode: "AU", flag: "🇦🇺"),
        Country(name: "Austria", code: "+43", isoCode: "AT", flag: "🇦🇹"),
        Country(name: "Azerbaijan", code: "+994", isoCode: "AZ", flag: "🇦🇿"),
        Country(name: "Bahamas", code: "+1-242", isoCode: "BS", flag: "🇧🇸"),
        Country(name: "Bahrain", code: "+973", isoCode: "BH", flag: "🇧🇭"),
        Country(name: "Bangladesh", code: "+880", isoCode: "BD", flag: "🇧🇩"),
        Country(name: "Barbados", code: "+1-246", isoCode: "BB", flag: "🇧🇧"),
        Country(name: "Belarus", code: "+375", isoCode: "BY", flag: "🇧🇾"),
        Country(name: "Belgium", code: "+32", isoCode: "BE", flag: "🇧🇪"),
        Country(name: "Belize", code: "+501", isoCode: "BZ", flag: "🇧🇿"),
        Country(name: "Benin", code: "+229", isoCode: "BJ", flag: "🇧🇯"),
        Country(name: "Bhutan", code: "+975", isoCode: "BT", flag: "🇧🇹"),
        Country(name: "Bolivia", code: "+591", isoCode: "BO", flag: "🇧🇴"),
        Country(name: "Bosnia and Herzegovina", code: "+387", isoCode: "BA", flag: "🇧🇦"),
        Country(name: "Botswana", code: "+267", isoCode: "BW", flag: "🇧🇼"),
        Country(name: "Brazil", code: "+55", isoCode: "BR", flag: "🇧🇷"),
        Country(name: "Brunei", code: "+673", isoCode: "BN", flag: "🇧🇳"),
        Country(name: "Bulgaria", code: "+359", isoCode: "BG", flag: "🇧🇬"),
        Country(name: "Burkina Faso", code: "+226", isoCode: "BF", flag: "🇧🇫"),
        Country(name: "Burundi", code: "+257", isoCode: "BI", flag: "🇧🇮"),
        Country(name: "Cabo Verde", code: "+238", isoCode: "CV", flag: "🇨🇻"),
        Country(name: "Cambodia", code: "+855", isoCode: "KH", flag: "🇨🇭"),
        Country(name: "Cameroon", code: "+237", isoCode: "CM", flag: "🇨🇲"),
        Country(name: "Canada", code: "+1", isoCode: "CA", flag: "🇨🇦"),
        Country(name: "Central African Republic", code: "+236", isoCode: "CF", flag: "🇨🇫"),
        Country(name: "Chad", code: "+235", isoCode: "TD", flag: "🇹🇩"),
        Country(name: "Chile", code: "+56", isoCode: "CL", flag: "🇨🇱"),
        Country(name: "China", code: "+86", isoCode: "CN", flag: "🇨🇳"),
        Country(name: "Colombia", code: "+57", isoCode: "CO", flag: "🇨🇴"),
        Country(name: "Comoros", code: "+269", isoCode: "KM", flag: "🇰🇲"),
        Country(name: "Congo (Congo-Brazzaville)", code: "+242", isoCode: "CG", flag: "🇨🇬"),
        Country(name: "Congo (DRC)", code: "+243", isoCode: "CD", flag: "🇨🇩"),
        Country(name: "Costa Rica", code: "+506", isoCode: "CR", flag: "🇨🇷"),
        Country(name: "Croatia", code: "+385", isoCode: "HR", flag: "🇨🇷"),
        Country(name: "Cuba", code: "+53", isoCode: "CU", flag: "🇨🇺"),
        Country(name: "Cyprus", code: "+357", isoCode: "CY", flag: "🇨🇾"),
        Country(name: "Czechia (Czech Republic)", code: "+420", isoCode: "CZ", flag: "🇨🇿"),
        Country(name: "Denmark", code: "+45", isoCode: "DK", flag: "🇩🇰"),
        Country(name: "Djibouti", code: "+253", isoCode: "DJ", flag: "🇩🇯"),
        Country(name: "Dominica", code: "+1-767", isoCode: "DM", flag: "🇩🇲"),
        Country(name: "Dominican Republic", code: "+1-809", isoCode: "DO", flag: "🇩🇴"),
        Country(name: "Ecuador", code: "+593", isoCode: "EC", flag: "🇪🇨"),
        Country(name: "Egypt", code: "+20", isoCode: "EG", flag: "🇪🇬"),
        Country(name: "El Salvador", code: "+503", isoCode: "SV", flag: "🇸🇻"),
        Country(name: "Equatorial Guinea", code: "+240", isoCode: "GQ", flag: "🇬🇶"),
        Country(name: "Eritrea", code: "+291", isoCode: "ER", flag: "🇪🇷"),
        Country(name: "Estonia", code: "+372", isoCode: "EE", flag: "🇪🇪"),
        Country(name: "Eswatini", code: "+268", isoCode: "SZ", flag: "🇸🇿"),
        Country(name: "Ethiopia", code: "+251", isoCode: "ET", flag: "🇪🇹"),
        Country(name: "Fiji", code: "+679", isoCode: "FJ", flag: "🇫🇯"),
        Country(name: "Finland", code: "+358", isoCode: "FI", flag: "🇫🇮"),
        Country(name: "France", code: "+33", isoCode: "FR", flag: "🇫🇷"),
        Country(name: "Gabon", code: "+241", isoCode: "GA", flag: "🇬🇲"),
        Country(name: "Gambia", code: "+220", isoCode: "GM", flag: "🇬🇲"),
        Country(name: "Georgia", code: "+995", isoCode: "GE", flag: "🇬🇪"),
        Country(name: "Germany", code: "+49", isoCode: "DE", flag: "🇩🇪"),
        Country(name: "Ghana", code: "+233", isoCode: "GH", flag: "🇬🇭"),
        Country(name: "Greece", code: "+30", isoCode: "GR", flag: "🇬🇷"),
        Country(name: "Grenada", code: "+1-473", isoCode: "GD", flag: "🇬🇩"),
        Country(name: "Guatemala", code: "+502", isoCode: "GT", flag: "🇬🇹"),
        Country(name: "Guinea", code: "+224", isoCode: "GN", flag: "🇬🇳"),
        Country(name: "Guinea-Bissau", code: "+245", isoCode: "GW", flag: "🇬🇼"),
        Country(name: "Guyana", code: "+592", isoCode: "GY", flag: "🇬🇾"),
        Country(name: "Haiti", code: "+509", isoCode: "HT", flag: "🇭🇹"),
        Country(name: "Honduras", code: "+504", isoCode: "HN", flag: "🇭🇳"),
        Country(name: "Hungary", code: "+36", isoCode: "HU", flag: "🇭🇺"),
        Country(name: "Iceland", code: "+354", isoCode: "IS", flag: "🇮🇸"),
        Country(name: "India", code: "+91", isoCode: "IN", flag: "🇮🇳"),
        Country(name: "Indonesia", code: "+62", isoCode: "ID", flag: "🇮🇩"),
        Country(name: "Iran", code: "+98", isoCode: "IR", flag: "🇮🇷"),
        Country(name: "Iraq", code: "+964", isoCode: "IQ", flag: "🇮🇶"),
        Country(name: "Ireland", code: "+353", isoCode: "IE", flag: "🇮🇪"),
        Country(name: "Israel", code: "+972", isoCode: "IL", flag: "🇮🇱"),
        Country(name: "Italy", code: "+39", isoCode: "IT", flag: "🇮🇹"),
        Country(name: "Jamaica", code: "+1-876", isoCode: "JM", flag: "🇯🇲"),
        Country(name: "Japan", code: "+81", isoCode: "JP", flag: "🇯🇵"),
        Country(name: "Jordan", code: "+962", isoCode: "JO", flag: "🇯🇴"),
        Country(name: "Kazakhstan", code: "+7", isoCode: "KZ", flag: "🇰🇿"),
        Country(name:"Kenya", code:"+254", isoCode:"KE", flag:"🇰🇪"),
       Country(name:"Kiribati", code:"+686", isoCode:"KI", flag:"🇰🇮"),
       Country(name:"Kuwait", code:"+965", isoCode:"KW", flag:"🇰🇼"),
       Country(name:"Kyrgyzstan", code:"+996", isoCode:"KG", flag:"🇰🇬"),
       Country(name:"Laos", code:"+856", isoCode:"LA", flag:"🇱🇦"),
       Country(name:"Latvia", code:"+371", isoCode:"LV", flag:"🇱🇻"),
       Country(name:"Lebanon", code:"+961", isoCode:"LB", flag:"🇱🇧"),
       Country(name:"Lesotho", code:"+266", isoCode:"LS", flag:"🇱🇸"),
       Country(name:"Liberia", code:"+231", isoCode:"LR", flag:"🇱🇷"),
       Country(name:"Libya", code:"+218", isoCode:"LY", flag:"🇱🇾"),
       Country(name:"Liechtenstein", code:"+423", isoCode:"LI", flag:"🇱🇮"),
       Country(name:"Lithuania", code:"+370", isoCode:"LT", flag:"🇱🇹"),
       Country(name:"Luxembourg", code:"+352", isoCode:"LU", flag:"🇱🇺"),
       Country(name:"Madagascar", code:"+261", isoCode:"MG", flag:"🇲🇬"),
    Country(name:"Malawi", code:"+265", isoCode:"MW", flag:"🇲🇼"),
       Country(name:"Malaysia", code:"+60", isoCode:"MY", flag:"🇲🇾"),
       Country(name:"Maldives", code:"+960", isoCode:"MV", flag:"🇲🇻"),
       Country(name:"Mali", code:"+223", isoCode:"ML", flag:"🇲🇱"),
       Country(name:"Malta", code:"+356", isoCode:"MT", flag:"🇲🇹"),
       Country(name:"Marshall Islands", code:"+692", isoCode:"MH", flag:"🇲🇭"),
       Country(name:"Mauritania", code:"+222", isoCode:"MR", flag:"🇲🇷"),
       Country(name:"Mauritius", code:"+230", isoCode:"MU", flag:"🇲🇺"),
       Country(name:"Mexico", code:"+52", isoCode:"MX", flag:"🇲🇽"),
       Country(name:"Micronesia", code:"+691", isoCode:"FM", flag:"🇫🇲"),
       Country(name:"Moldova", code:"+373", isoCode:"MD", flag:"🇲🇩"),
       Country(name:"Monaco", code:"+377", isoCode:"MC", flag:"🇲🇨"),
       Country(name:"Mongolia", code:"+976", isoCode:"MN", flag:"🇲🇳"),
       Country(name:"Montenegro", code:"+382", isoCode:"ME", flag:"🇲🇪"),
       Country(name:"Morocco", code:"+212", isoCode:"MA", flag:"🇲🇦"),
       Country(name:"Mozambique", code:"+258", isoCode:"MZ", flag:"🇲🇿"),
       Country(name:"Myanmar", code:"+95", isoCode:"MM", flag:"🇲🇲"),
       Country(name:"Namibia", code:"+264", isoCode:"NA", flag:"🇳🇦"),
       Country(name:"Nauru", code:"+674", isoCode:"NR", flag:"🇳🇷"),
       Country(name:"Nepal", code:"+977", isoCode:"NP", flag:"🇳🇵"),
       Country(name:"Netherlands", code:"+31", isoCode:"NL", flag:"🇳🇱"),
       Country(name:"New Zealand", code:"+64", isoCode:"NZ", flag:"🇳🇿"),
       Country(name:"Nicaragua", code:"+505", isoCode:"NI", flag:"🇳🇮"),
       Country(name:"Niger", code:"+227", isoCode:"NE", flag:"🇳🇪"),
       Country(name:"Nigeria", code:"+234", isoCode:"NG", flag:"🇳🇬"),
       Country(name:"North Korea", code:"+850", isoCode:"KP", flag:"🇰🇵"),
       Country(name:"North Macedonia", code:"+389", isoCode:"MK", flag:"🇲🇰"),
       Country(name:"Norway", code:"+47", isoCode:"NO", flag:"🇳🇴"),
       Country(name:"Oman", code:"+968", isoCode:"OM", flag:"🇴🇲"),
       Country(name:"Pakistan", code:"+92", isoCode:"PK", flag:"🇵🇰"),
       Country(name:"Palau", code:"+680", isoCode:"PW", flag:"🇵🇼"),
       Country(name:"Palestine State", code:"+970", isoCode:"PS", flag:"🇵🇸"),
       Country(name:"Panama", code:"+507", isoCode:"PA", flag:"🇵🇦"),
       Country(name:"Papua New Guinea", code:"+675", isoCode:"PG", flag:"🇵🇬"),
       Country(name:"Paraguay", code:"+595", isoCode:"PY", flag:"🇵🇾"),
       Country(name:"Peru", code:"+51", isoCode:"PE", flag:"🇵🇪"),
       Country(name:"Philippines", code:"+63", isoCode:"PH", flag:"🇵🇭"),
       Country(name:"Poland", code:"+48", isoCode:"PL", flag:"🇵🇱"),
       Country(name:"Portugal", code:"+351", isoCode:"PT", flag:"🇵🇹"),
       Country(name:"Qatar", code:"+974", isoCode:"QA", flag:"🇶🇦"),
       Country(name:"Romania", code:"+40", isoCode:"RO", flag:"🇷🇴"),
       Country(name:"Russia", code:"+7", isoCode:"RU", flag:"🇷🇺"),
       Country(name:"Rwanda", code:"+250", isoCode:"RW", flag:"🇷🇼"),
       Country(name:"Saint Kitts and Nevis", code:"+1-869", isoCode:"KN", flag:"🇰🇳"),
       Country(name:"Saint Lucia", code:"+1-758", isoCode:"LC", flag:"🇱🇨"),
       Country(name:"Saint Vincent and the Grenadines", code:"+1-784", isoCode:"VC", flag:"🇻🇨"),
       Country(name:"Samoa", code:"+685", isoCode:"WS", flag:"🇼🇸"),
       Country(name:"San Marino", code:"+378", isoCode:"SM", flag:"🇸🇲"),
       Country(name:"Sao Tome and Principe", code:"+239", isoCode:"ST", flag:"🇸🇹"),
       Country(name:"Saudi Arabia", code:"+966", isoCode:"SA", flag:"🇸🇦"),
       Country(name:"Senegal", code:"+221", isoCode:"SN", flag:"🇸🇳"),
       Country(name:"Serbia", code:"+381", isoCode:"RS", flag:"🇷🇸"),
       Country(name:"Seychelles", code:"+248", isoCode:"SC", flag:"🇸🇨"),
       Country(name:"Sierra Leone", code:"+232", isoCode:"SL", flag:"🇸🇱"),
       Country(name:"Singapore", code:"+65", isoCode:"SG", flag:"🇸🇬"),
       Country(name:"Slovakia", code:"+421", isoCode:"SK", flag:"🇸🇰"),
       Country(name:"Slovenia", code:"+386", isoCode:"SI", flag:"🇸🇮"),
       Country(name:"Solomon Islands", code:"+677", isoCode:"SB", flag:"🇸🇧"),
       Country(name:"Somalia", code:"+252", isoCode:"SO", flag:"🇸🇴"),
       Country(name:"South Africa", code:"+27", isoCode:"ZA", flag:"🇿🇦"),
       Country(name:"South Korea", code:"+82", isoCode:"KR", flag:"🇰🇷"),
       Country(name:"South Sudan", code:"+211", isoCode:"SS", flag:"🇸🇸"),
       Country(name:"Spain", code:"+34", isoCode:"ES", flag:"🇪🇸"),
       Country(name:"Sri Lanka", code:"+94", isoCode:"LK", flag:"🇱🇰"),
       Country(name:"Sudan", code:"+249", isoCode:"SD", flag:"🇸🇩"),
       Country(name:"Suriname", code:"+597", isoCode:"SR", flag:"🇸🇷"),
       Country(name:"Sweden", code:"+46", isoCode:"SE", flag:"🇸🇪"),
       Country(name:"Switzerland", code:"+41", isoCode:"CH", flag:"🇨🇭"),
       Country(name:"Syria", code:"+963", isoCode:"SY", flag:"🇸🇾"),
       Country(name:"Taiwan", code:"+886", isoCode:"TW", flag:"🇹🇼"),
       Country(name:"Tajikistan", code:"+992", isoCode:"TJ", flag:"🇹🇯"),
       Country(name:"Tanzania", code:"+255", isoCode:"TZ", flag:"🇹🇿"),
       Country(name:"Thailand", code:"+66", isoCode:"TH", flag:"🇹🇭"),
       Country(name:"Timor-Leste", code:"+670", isoCode:"TL", flag:"🇹🇱"),
       Country(name:"Togo", code:"+228", isoCode:"TG", flag:"🇹🇬"),
       Country(name:"Tonga", code:"+676", isoCode:"TO", flag:"🇹🇴"),
       Country(name:"Trinidad and Tobago", code:"+1-868", isoCode:"TT", flag:"🇹🇹"),
       Country(name:"Tunisia", code:"+216", isoCode:"TN", flag:"🇹🇳"),
       Country(name:"Turkey", code:"+90", isoCode:"TR", flag:"🇹🇷"),
       Country(name:"Turkmenistan", code:"+993", isoCode:"TM", flag:"🇹🇲"),
       Country(name:"Tuvalu", code:"+688", isoCode:"TV", flag:"🇹🇻"),
        Country(name:"Uganda", code:"+256", isoCode:"UG", flag:"🇺🇬"),
            Country(name:"Ukraine", code:"+380", isoCode:"UA", flag:"🇺🇦"),
            Country(name:"United Arab Emirates", code:"+971", isoCode:"AE", flag:"🇦🇪"),
            Country(name:"United Kingdom", code:"+44", isoCode:"GB", flag:"🇬🇧"),
            Country(name:"United States", code:"+1", isoCode:"US", flag:"🇺🇸"),
            Country(name:"Uruguay", code:"+598", isoCode:"UY", flag:"🇺🇾"),
            Country(name:"Uzbekistan", code:"+998", isoCode:"UZ", flag:"🇺🇿"),
            Country(name:"Vanuatu", code:"+678", isoCode:"VU", flag:"🇻🇺"),
            Country(name:"Vatican City", code:"+379", isoCode:"VA", flag:"🇻🇦"),
            Country(name:"Venezuela", code:"+58", isoCode:"VE", flag:"🇻🇪"),
            Country(name:"Vietnam", code:"+84", isoCode:"VN", flag:"🇻🇳"),
            Country(name:"Yemen", code:"+967", isoCode:"YE", flag:"🇾🇪"),
            Country(name:"Zambia", code:"+260", isoCode:"ZM", flag:"🇿🇲"),
            Country(name:"Zimbabwe", code:"+263", isoCode:"ZW", flag:"🇿🇼"),
]
